version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - /linyu/mysql:/var/lib/mysql

  linyu-mini-web:
    image: henam/linyu-mini-web:latest
    container_name: linyu-mini-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /linyu/nginx/ssl:/etc/nginx/ssl
      - /linyu/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - linyu-mini-server
    environment:
      SERVER_NAME: ${SERVER_NAME}
      SERVER_HTTP_URL: https://${SERVER_NAME}
      SERVER_WS_URL: wss://${SERVER_NAME}

  linyu-mini-server:
    image: henam/linyu-mini-server:latest
    container_name: linyu-mini-server
    volumes:
      - /linyu/data:/linyu/data
      - /linyu/logs:/linyu/logs
    ports:
      - "9100:9100"
      - "9200:9200"
    depends_on:
      - mysql
    environment:
      SQLITE_FILE_PATH: ${SQLITE_FILE_PATH}
      LINYU_LOG_PATH: ${LINYU_LOG_PATH}
      LINYU_PASSWORD: ${LINYU_PASSWORD}
      LINYU_LIMIT: ${LINYU_LIMIT}
      LINYU_NAME: ${LINYU_NAME}
      LINYU_EXPIRES: ${LINYU_EXPIRES}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      LINYU_DOUBAO_API_KEY: ${LINYU_DOUBAO_API_KEY}
      LINYU_DOUBAO_COUNT_LIMIT: ${LINYU_DOUBAO_COUNT_LIMIT}
      LINYU_DOUBAO_LENGTH_LIMIT: ${LINYU_DOUBAO_LENGTH_LIMIT}
      LINYU_DOUBAO_MODEL: ${LINYU_DOUBAO_MODEL}
      LINYU_DEEPSEEK_API_KEY: ${LINYU_DEEPSEEK_API_KEY}
      LINYU_DEEPSEEK_COUNT_LIMIT: ${LINYU_DEEPSEEK_COUNT_LIMIT}
      LINYU_DEEPSEEK_LENGTH_LIMIT: ${LINYU_DEEPSEEK_LENGTH_LIMIT}
      LINYU_DEEPSEEK_MODEL: ${LINYU_DEEPSEEK_MODEL}