server:
  port: 9200

spring:
  datasource:
    #sqlite
    url: jdbc:sqlite:${SQLITE_FILE_PATH} #数据库文件路径（修改成实际路径）
    driver-class-name: org.sqlite.JDBC
    username:
    password:
  #mysql配置
  #      driver-class-name: com.mysql.cj.jdbc.Driver
  #      url: jdbc:mysql://127.0.0.1:3306/linyu-mini?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  #      username: root
  #      password: 123456
  hikari:
    minimum-idle: 3
    maximum-pool-size: 10
    max-lifetime: 30000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: Asia/Shanghai

logging:
  file:
    name: ${LINYU_LOG_PATH}

mybatis:
  table:
    auto: update

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

linyu:
  password: ${LINYU_PASSWORD} #群聊密码
  limit: ${LINYU_LIMIT} #在线人数限制
  name: ${LINYU_NAME} #群聊名称